import { Skeleton } from '@/components/ui/skeleton';

export default function CardsLoading() {
  return (
    <div className="flex flex-col gap-4 pb-6" role="status" aria-label="Loading cards">
      <span className="sr-only">Loading cards</span>
      <div className="overflow-hidden rounded-2xl border border-border/60 bg-card px-5 pb-5 pt-3 sm:px-6 sm:pb-6 sm:pt-4"><div className="flex items-center gap-4"><Skeleton className="size-14 rounded-2xl" /><div className="flex-1 space-y-2"><Skeleton className="h-5 w-32" /><Skeleton className="h-3 w-56" /><Skeleton className="h-2.5 w-72" /></div><div className="flex gap-2"><Skeleton className="h-8 w-20 rounded-lg" /><Skeleton className="h-8 w-24 rounded-lg" /></div></div><div className="mt-5 grid grid-cols-2 gap-2 border-t border-border/50 pt-5 sm:grid-cols-4">{[0, 1, 2, 3].map((item) => <div key={item} className="flex items-center gap-2.5 rounded-xl border border-border/50 bg-background/60 px-3 py-2.5"><Skeleton className="size-8 rounded-lg" /><div className="space-y-2"><Skeleton className="h-2.5 w-20" /><Skeleton className="h-4 w-12" /></div></div>)}</div></div>
      <div className="overflow-hidden rounded-2xl border border-border/60 bg-card"><div className="flex items-center justify-between border-b border-border/50 px-5 py-3"><div className="flex items-center gap-3"><Skeleton className="size-9 rounded-xl" /><div className="space-y-2"><Skeleton className="h-4 w-28" /><Skeleton className="h-2.5 w-48" /></div></div><Skeleton className="h-8 w-24 rounded-lg" /></div><div className="grid grid-cols-1 gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">{[0, 1, 2].map((item) => <div key={item} className="space-y-3"><Skeleton className="h-[180px] w-full rounded-2xl" /><Skeleton className="h-3 w-24" /><Skeleton className="h-2.5 w-20" /></div>)}<Skeleton className="h-[180px] w-full rounded-2xl border border-dashed border-border/60 bg-accent/40" /></div></div>
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><div className="flex flex-col gap-4 lg:col-span-2"><div className="overflow-hidden rounded-2xl border border-border/60 bg-card"><div className="flex items-center justify-between border-b border-border/50 px-5 py-3"><Skeleton className="h-4 w-32" /><Skeleton className="h-8 w-20 rounded-lg" /></div><div className="overflow-x-auto px-5">{[0, 1, 2, 3].map((item) => <div key={item} className="flex min-w-[700px] items-center gap-6 border-b border-border/30 py-4 last:border-0"><Skeleton className="h-3 w-8" /><Skeleton className="h-3 w-28" /><Skeleton className="h-3 w-24" /><Skeleton className="h-3 w-24" /><Skeleton className="ml-auto h-4 w-20" /><Skeleton className="h-5 w-14 rounded-full" /></div>)}</div></div></div><div className="flex flex-col gap-4"><Skeleton className="h-64 rounded-2xl" /><Skeleton className="h-72 rounded-2xl" /><Skeleton className="h-56 rounded-2xl" /></div></div>
    </div>
  );
}
