import { Skeleton } from '@/components/ui/skeleton';

export default function TaxesLoading() {
  return (
    <div className="flex flex-col gap-4 pb-6" role="status" aria-label="Loading tax documents">
      <span className="sr-only">Loading tax documents</span>
      <div className="overflow-hidden rounded-2xl border border-border/60 bg-card"><div className="flex items-center justify-between gap-4 px-5 pb-5 pt-3"><div className="flex items-center gap-4"><Skeleton className="size-14 rounded-2xl" /><div className="space-y-2"><Skeleton className="h-5 w-32" /><Skeleton className="h-3 w-52" /><Skeleton className="h-2.5 w-64" /></div></div><div className="flex gap-2"><Skeleton className="h-8 w-24 rounded-lg" /><Skeleton className="h-8 w-20 rounded-lg" /></div></div><div className="grid grid-cols-2 gap-px border-t border-border/40 bg-border/20 sm:grid-cols-4">{[0, 1, 2, 3].map((item) => <div key={item} className="flex items-center gap-3 bg-card/80 px-4 py-3.5"><Skeleton className="size-8 rounded-xl" /><div className="space-y-2"><Skeleton className="h-2.5 w-20" /><Skeleton className="h-4 w-16" /></div></div>)}</div></div>
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><div className="flex flex-col gap-4 lg:col-span-2"><div className="overflow-hidden rounded-2xl border border-border/60 bg-card"><div className="flex items-center justify-between border-b border-border/50 px-5 py-3"><div className="space-y-2"><Skeleton className="h-4 w-32" /><Skeleton className="h-2.5 w-48" /></div><Skeleton className="h-7 w-24 rounded-lg" /></div><div className="flex gap-2 border-b border-border/40 bg-muted/20 px-5 py-3"><Skeleton className="h-7 flex-1 rounded-lg" /><Skeleton className="h-7 w-24 rounded-lg" /><Skeleton className="h-7 w-24 rounded-lg" /></div><div className="overflow-x-auto px-4">{[0, 1, 2, 3, 4].map((item) => <div key={item} className="flex min-w-[580px] items-center gap-6 border-b border-border/30 py-4 last:border-0"><div className="flex w-40 items-center gap-3"><Skeleton className="size-8 rounded-lg" /><Skeleton className="h-3 w-28" /></div><Skeleton className="h-3 w-20" /><Skeleton className="h-3 w-16" /><Skeleton className="h-3 w-20" /><Skeleton className="h-5 w-16 rounded-full" /><Skeleton className="ml-auto size-7 rounded-md" /></div>)}</div></div><div className="rounded-2xl border border-border/60 bg-card p-5"><Skeleton className="h-4 w-44" /><div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2">{[0, 1, 2, 3].map((item) => <div key={item} className="rounded-xl border border-border/50 bg-muted/20 p-4"><div className="flex justify-between"><Skeleton className="h-4 w-20" /><Skeleton className="h-5 w-12 rounded-full" /></div><div className="mt-5 space-y-2"><Skeleton className="h-3 w-full" /><Skeleton className="h-3 w-4/5" /></div><Skeleton className="mt-4 h-1.5 w-full rounded-full" /></div>)}</div></div></div><div className="flex flex-col gap-4"><Skeleton className="h-56 rounded-2xl" /><Skeleton className="h-64 rounded-2xl" /><Skeleton className="h-48 rounded-2xl" /><Skeleton className="h-40 rounded-2xl" /></div></div>
    </div>
  );
}
